export const ADD_ADMIN="ADMIN_ADMIN";
export const LOGIN_ADMIN="LOGIN_ADMIN";
export const ADMIN="ADMIN";
export const DELETE_ADMIN="DELETE_ADMIN";

// message
export const USER_CONTAIN="USER_CONTAIN";
export const USER_REGISTER="USER_REGISTER";


export const LOGIN_ADMIN_IN="LOGIN_ADMIN_IN";
export const LOGIN_ADMIN_SUCCESS="LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_ERROR="LOGIN_ADMIN_ERROR";


export const admin_Get='Admin_Get';



// login
export const LOGOUT_ADMIN_IN='LOGOUT_ADMIN_IN';
export const LOGOUT_ADMIN_SUCCESS='LOGOUT_ADMIN_SUCCESS';
export const LOGOUT_ADMIN_ERROR='LOGOUT_ADMIN_ERROR';


export const REGISTER_IN_ADMIN='REGISTER_IN_ADMIN';
export const REGISTER_SUCCESS_ADMIN='REGISTER_SUCCESS_ADMIN';
export const REGISTER_ERO_ADMIN='REGISTER_ERO_ADMIN';



export const UPDATE_ADMIN_IN='UPDATE_ADMIN_IN';
export const UPDATE_ADMIN_SUCCESS='UPDATE_ADMIN_SUCCESS';
export const UPDATE_ADMIN_ERO='UPDATE_ADMIN_ERO';


export const RESET_REGISTER_ADMIN="RESET_REGISTER_ADMIN";
export const GET_ACCOUNT_ADMIN="GET_ACCOUNT_ADMIN";