export const BILL_UPDATE_REQUEST='BILL_UPDATE_REQUEST';
export const BILL_UPDATE_SUCCESS='BILL_UPDATE_SUCCESS';
export const BILL_UPDATE_ERROR='BILL_UPDATE_ERROR';
export const Reset_Update_Bill='Reset_Update_Bill'


export const BILL_DELETE_REQUEST='BILL_DELETE_REQUEST';
export const BILL_DELETE_SUCCESS='BILL_DELETE_SUCCESS';
export const BILL_DELETE_ERROR='BILL_DELETE_ERROR';
export const Reset_DELETE_Bill='Reset_DELETE_Bill'