export const ALL_PRODUCT="ALL_PRODUCT";
export const ADD_PRODUCT="ADD_PRODUCT";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";

export const FILTER_DATA='FILTER_DATA';



export const DELETE_REVIEW_IN='DELETE_REVIEW_IN';

export const DELETE_REVIEW_SUCCESS='DELETE_REVIEW_SUCCESS';

export const DELETE_REVIEW_ERR='DELETE_REVIEW_ERR';

export const RESET_REVIEW='RESET_REVIEW';