export const ADD_SLIDES='ADD_SLIDES';
export const ADD_SLIDES_REQUEST='ADD_SLIDES_REQUEST';
export const ADD_SLIDES_SUCCESS='ADD_SLIDES_SUCCESS';
export const ADD_SLIDES_ERROR='ADD_SLIDES_ERROR';


export const DELETE_SLIDES='DELETE_SLIDES';
export const DELETE_SLIDES_REQUEST='DELETE_SLIDES_REQUEST';
export const DELETE_SLIDES_SUCCESS='DELETE_SLIDES_SUCCESS';
export const DELETE_SLIDES_ERROR='DELETE_SLIDES_ERROR';


export const UPDATE_STATUS_SLIDES='UPDATE_STATUS_SLIDES';
export const UPDATE_STATUS_SLIDES_REQUEST='UPDATE_STATUS_SLIDES_REQUEST';
export const UPDATE_STATUS_SLIDES_SUCCESS='UPDATE_STATUS_SLIDES_SUCCESS';
export const UPDATE_STATUS_SLIDES_ERROR='DELETE_SLIDES_ERROR';

export const RESET_SLIDES='RESET_SLIDES';